/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patronestado;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import patronestado.estados.PrestamoRealizado;
import patronestado.estados.PrestamoSolicitado;

/**
 *
 * @author Usuario
 */
public class Cliente extends javax.swing.JFrame {

    //Prestamo prestamo = new Prestamo();
    private ArrayList<Prestamo> prestamos = new ArrayList<Prestamo>();
    private int cantidad;
    private String idPrestamo;
    DefaultTableModel modelo;
    String[] datos;

    /**
     * Creates new form Clien
     */
    public Cliente() {
        initComponents();
        cantidad = 1;
        prestamos.add(new Prestamo());
        prestamos.get(0).setNombrePrestamo("Préstamo " + String.valueOf(cantidad));

        //Tabla de préstamos
        modelo = new DefaultTableModel();

        modelo.addColumn("ID");
        modelo.addColumn("PRÉSTAMO");
        modelo.addColumn("ESTADO");

        datos = new String[3];
        datos[0] = String.valueOf(cantidad);
        datos[1] = prestamos.get(0).getNombrePrestamo();
        datos[2] = prestamos.get(0).getMensaje();

        modelo.addRow(datos);
        this.prestamosTabla.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        solicitarBoton = new javax.swing.JButton();
        devolverBoton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        enEsperaBoton = new javax.swing.JButton();
        aceptarBoton = new javax.swing.JButton();
        rechazarBoton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prestamosTabla = new javax.swing.JTable();
        nuevoBoton = new javax.swing.JButton();
        text = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(194, 156, 5));

        solicitarBoton.setBackground(new java.awt.Color(0, 0, 0));
        solicitarBoton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        solicitarBoton.setForeground(new java.awt.Color(255, 255, 255));
        solicitarBoton.setText("SOLICITAR");
        solicitarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitarBotonActionPerformed(evt);
            }
        });

        devolverBoton.setBackground(new java.awt.Color(0, 0, 0));
        devolverBoton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        devolverBoton.setForeground(new java.awt.Color(255, 255, 255));
        devolverBoton.setText("DEVOLVER");
        devolverBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverBotonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("PRÉSTAMO ACTIVO:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("EL PATRÓN ESTADO");

        enEsperaBoton.setBackground(new java.awt.Color(0, 0, 0));
        enEsperaBoton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        enEsperaBoton.setForeground(new java.awt.Color(255, 255, 255));
        enEsperaBoton.setText("COLOCAR EN ESPERA");
        enEsperaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enEsperaBotonActionPerformed(evt);
            }
        });

        aceptarBoton.setBackground(new java.awt.Color(0, 0, 0));
        aceptarBoton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        aceptarBoton.setForeground(new java.awt.Color(255, 255, 255));
        aceptarBoton.setText("ACEPTAR");
        aceptarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBotonActionPerformed(evt);
            }
        });

        rechazarBoton.setBackground(new java.awt.Color(0, 0, 0));
        rechazarBoton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rechazarBoton.setForeground(new java.awt.Color(255, 255, 255));
        rechazarBoton.setText("RECHAZAR");
        rechazarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechazarBotonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("ACCIONES");

        prestamosTabla.setBackground(new java.awt.Color(247, 208, 63));
        prestamosTabla.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        prestamosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "PRÉSTAMO", "ESTADO"
            }
        ));
        prestamosTabla.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(prestamosTabla);

        nuevoBoton.setBackground(new java.awt.Color(0, 0, 0));
        nuevoBoton.setForeground(new java.awt.Color(255, 255, 255));
        nuevoBoton.setText("NUEVO PRÉSTAMO");
        nuevoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(rechazarBoton)
                                        .addGap(49, 49, 49)
                                        .addComponent(aceptarBoton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(solicitarBoton)
                                        .addGap(36, 36, 36)
                                        .addComponent(devolverBoton)
                                        .addGap(39, 39, 39)
                                        .addComponent(enEsperaBoton))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(nuevoBoton)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(devolverBoton)
                    .addComponent(enEsperaBoton)
                    .addComponent(solicitarBoton))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rechazarBoton)
                    .addComponent(aceptarBoton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nuevoBoton)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void solicitarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitarBotonActionPerformed
        // TODO add your handling code here:
        idPrestamo = text.getText();
        if ("".equals(idPrestamo)) {
            JOptionPane.showMessageDialog(null,
                    "Acción inválida: Por favor rellene el campo préstamo activo");
            text.requestFocus();
        } else if (Integer.parseInt(idPrestamo) > cantidad) {
            JOptionPane.showMessageDialog(null,
                    "Acción inválida: Préstamo no existente");
            text.requestFocus();
        } else {
            prestamos.get(Integer.parseInt(idPrestamo) - 1).solicitando();
            actualizar(Integer.parseInt(idPrestamo) - 1);
            text.requestFocus();
        }
    }//GEN-LAST:event_solicitarBotonActionPerformed

    private void devolverBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverBotonActionPerformed
        // TODO add your handling code here:  
        idPrestamo = text.getText();
        if ("".equals(idPrestamo)) {
            JOptionPane.showMessageDialog(null,
                    "Acción inválida: Por favor rellene el campo préstamo activo");
            text.requestFocus();
        } else if (Integer.parseInt(idPrestamo) > cantidad) {
            JOptionPane.showMessageDialog(null,
                    "Acción inválida: Préstamo no existente");
            text.requestFocus();
        } else {
            prestamos.get(Integer.parseInt(idPrestamo) - 1).devolviendo();
            actualizar(Integer.parseInt(idPrestamo) - 1);
            text.requestFocus();
        }
    }//GEN-LAST:event_devolverBotonActionPerformed

    private void enEsperaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enEsperaBotonActionPerformed
        // TODO add your handling code here:
        idPrestamo = text.getText();
        if ("".equals(idPrestamo)) {
            JOptionPane.showMessageDialog(null,
                    "Acción inválida: Por favor rellene el campo préstamo activo");
            text.requestFocus();
        } else if (Integer.parseInt(idPrestamo) > cantidad) {
            JOptionPane.showMessageDialog(null,
                    "Acción inválida: Préstamo no existente");
            text.requestFocus();
        } else {
            prestamos.get(Integer.parseInt(idPrestamo) - 1).esperandoSolicitud();
            actualizar(Integer.parseInt(idPrestamo) - 1);
            text.requestFocus();
        }
    }//GEN-LAST:event_enEsperaBotonActionPerformed

    private void rechazarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechazarBotonActionPerformed
        // TODO add your handling code here:
        idPrestamo = text.getText();
        if ("".equals(idPrestamo)) {
            JOptionPane.showMessageDialog(null,
                    "Acción inválida: Por favor rellene el campo préstamo activo");
            text.requestFocus();
        } else if (Integer.parseInt(idPrestamo) > cantidad) {
            JOptionPane.showMessageDialog(null,
                    "Acción inválida: Préstamo no existente");
            text.requestFocus();
        } else {
            prestamos.get(Integer.parseInt(idPrestamo) - 1).prestamoRechazado();
            actualizar(Integer.parseInt(idPrestamo) - 1);
            text.requestFocus();
        }
    }//GEN-LAST:event_rechazarBotonActionPerformed

    private void aceptarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBotonActionPerformed
        // TODO add your handling code here:
        idPrestamo = text.getText();
        if ("".equals(idPrestamo)) {
            JOptionPane.showMessageDialog(null,
                    "Acción inválida: Por favor rellene el campo préstamo activo");
            text.requestFocus();
        } else if (Integer.parseInt(idPrestamo) > cantidad) {
            JOptionPane.showMessageDialog(null,
                    "Acción inválida: Préstamo no existente");
            text.requestFocus();
        } else {
            prestamos.get(Integer.parseInt(idPrestamo) - 1).prestamoConfirmado();
            actualizar(Integer.parseInt(idPrestamo) - 1);
            text.requestFocus();
        }
    }//GEN-LAST:event_aceptarBotonActionPerformed

    private void nuevoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoBotonActionPerformed
        // TODO add your handling code here:
        cantidad++;
        prestamos.add(new Prestamo());
        prestamos.get(cantidad - 1).setNombrePrestamo("Préstamo "
                + String.valueOf(cantidad));
        datos[0] = String.valueOf(cantidad);
        datos[1] = prestamos.get(cantidad - 1).getNombrePrestamo();
        datos[2] = prestamos.get(cantidad - 1).getMensaje();
        modelo.addRow(datos);
        text.requestFocus();
    }//GEN-LAST:event_nuevoBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cliente cliente = new Cliente();
                cliente.setVisible(true);
                cliente.setLocationRelativeTo(null);
            }

        });

    }

    private void actualizar(int pos) {
        modelo.setValueAt(prestamos.get(pos).getMensaje(), pos, 2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarBoton;
    private javax.swing.JButton devolverBoton;
    private javax.swing.JButton enEsperaBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nuevoBoton;
    private javax.swing.JTable prestamosTabla;
    private javax.swing.JButton rechazarBoton;
    private javax.swing.JButton solicitarBoton;
    private javax.swing.JTextField text;
    // End of variables declaration//GEN-END:variables
}
